#!/bin/sh

echo ""

if [ ! -f "vendor/bin/phpstan" ]
then
    echo "PHPStan not found."
    exit 0
fi

VAR=$(git diff --cached --name-only --diff-filter=AM)

if [ ! "$VAR" ];then
   echo "Nothing to check"
   exit 0
fi

echo "$stdin" | vendor/bin/phpstan analyse --level 0 --autoload-file vendor/autoload.php $VAR "$@"
exit_code=$?
exit $exit_code
